pipeline:
  setting: 'test_run'  #options: 'service', 'research', or 'all'. Select 'service' with minimal rules for providing services. Select 'research' with rules for research purposes, select them in Snakefile under rule research. For all rules select 'all'.
  THREADS: 4
  suppressMessages: TRUE #options TRUE or FALSE, TRUE for suppressed library messages and warnings of R-packages

#--------------------------------------------------------------------------------------------------------------------
#
# Input and Output:

path:
  dir_bam: "../CNP20-028/bam/" #"/mnt/shared/input_dir/bam/" #
  dir_out: "../CNP20-028/results/" #"/mnt/shared/output_dir/resultReport/" # directory where the output should be created, all other directories below are branches of this directory
  #
  #-------------------------------------------
  dir_stats: "stats/"
  dir_log: "log/"

#_______________________________________________________________Advanced_Configurations________________________________________________________________________________________________
summary:
  profiletypes: ["corrected", "segmented", "called",'dewaved']


QDNAseq:
  BINSIZES: ["100", "1000"]   #required binsizes comma seperated  1 5 10 15 30 100 1000
  genome: hg19
  chrom_filter: ["Y", "X"] # comma separated quoted to specify which chromosomes to filter out. "X","Y"
  dewave: False #dewaving is an optional setting, if True samples will be dewaved before segmentation, if False dewaving will be skipped.
  dewave_dir: scripts/QDNAseq.dev-dewave/R
  dewave_data: scripts/QDNAseq.dev-dewave/data_ionTurrent/NormalCalibrationSet_{binSize}kb.rda #!!!  
  #scripts/QDNAseq.dev-dewave/data/NormalCalibrationSet_{binSize}kb.rda
  #dewave_data: data/NormalCalibrationSet_{binSize}kb.rda
  minimal_used_reads: 100000
  minimum_cellularity: 0.2  # minimum cellularity used for calling, a to low cellularity cause over calling.
  seg_alpha: 1e-10 #1e-50 # 1e-10 #adjust in case of over-segmentation
  seg_undoSD: 1  #1.5 # 1 #adjust in case of over-segmentation

ACE:
  ploidies: [2] # [2,4]   #required ploidies comma seperated
  main_ploidy: 2   # only the main ploidy fitpicker file will be used for calling based on cellularity
  imagetype: png      #options are png, pdf
  method: RMSE        #'RMSE' root mean squared error, 'MAE' weighs every error equally, 'SMRE' punish more the long segments that are a little bit off compared to the short segments that are way off
  penalty: 0.5          #sets a penalty for the error calculated at lower cellularity
  cap: 12             # which copy numbers are capped (highest value)
  trncname: FALSE     #Samplenames are truncated after _
  printsummaries: FALSE  #options: TRUE, FALSE or 2, TRUE is only possible for less than ~ 50 samples. 2 means that only the errorplots are in a summary file.
  ACEBINSIZES: [100, 1000] #required binsizes comma seperated 15 30 100 1000, be careful not to ask for binsizes not created by QDNAseq. Smaller binsizes are computationally harder.


Clonality:
  reference: scripts/d4-pipeline-master/data/Corrected_Imp_raw_output_Ref08.txt
  # carcinoma_type: "LUAD" # default
  # LUAD_reference: LUAD.txt
  # LUSC_reference: LUSC.txt

